# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-08 04:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u8bf7\u8f93\u5165\u6750\u6599\u540d\uff1a', max_length=128, unique=True, verbose_name='\u6750\u6599\u540d')),
                ('code', models.CharField(help_text='\u8bf7\u8f93\u5165\u6750\u6599\u89c4\u683c\uff1a', max_length=128, null=True, verbose_name='\u6750\u6599\u89c4\u683c')),
                ('inventory', models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u5e93\u5b58\u6570\u91cf\uff1a', null=True, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('used', models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u5df2\u7528\u6570\u91cf\uff1a', null=True, verbose_name='\u5df2\u7528\u6570\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u8bf7\u8f93\u5165\u5de5\u5e8f\u540d\uff1a', max_length=128, verbose_name='\u5de5\u5e8f\u540d')),
                ('code', models.CharField(default='', help_text='\u8bf7\u8f93\u5165\u5de5\u5e8f\u4ee3\u7801\uff1a', max_length=16, null=True, verbose_name='\u5de5\u5e8f\u4ee3\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_num', models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u5b9a\u989d\u6570\u91cf\uff1a', null=True, verbose_name='\u5b9a\u989d\u6570\u91cf')),
                ('produce_num', models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u751f\u4ea7\u6570\u91cf\uff1a', null=True, verbose_name='\u751f\u4ea7\u6570\u91cf')),
                ('process_des', models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u4f5c\u4e1a\u8981\u70b9\u6307\u5bfc\uff1a', null=True, verbose_name='\u4f5c\u4e1a\u8981\u70b9\u6307\u5bfc')),
                ('detect_log', models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u9996\u68c0\u8bb0\u5f55\uff1a', null=True, verbose_name='\u9996\u68c0\u8bb0\u5f55')),
                ('inspect_log', models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u5de1\u68c0\u8bb0\u5f55\uff1a', null=True, verbose_name='\u5de1\u68c0\u8bb0\u5f55')),
                ('inspect_date', models.DateField(blank=True, default=datetime.datetime.now, help_text='\u8bf7\u8f93\u5165\u65e5\u671f\uff1a', max_length=8, verbose_name='\u65e5\u671f')),
                ('inspector', models.CharField(blank=True, help_text='\u8bf7\u8f93\u5165\u5de1\u68c0\u5458\uff1a', max_length=16, null=True, verbose_name='\u5de1\u68c0\u5458')),
                ('description', models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u5907\u6ce8\uff1a', null=True, verbose_name='\u5907\u6ce8')),
                ('material', models.ForeignKey(blank=True, help_text='\u8bf7\u9009\u62e9\u6750\u6599\u89c4\u683c\uff1a', null=True, on_delete=django.db.models.deletion.CASCADE, to='lonfly.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(help_text='\u8bf7\u8f93\u5165\u4ea7\u54c1\u6807\u8bc6\uff1a', max_length=8, primary_key=True, serialize=False, verbose_name='\u4ea7\u54c1ID')),
                ('product_name', models.CharField(help_text='\u8bf7\u8f93\u5165\u4ea7\u54c1\u540d\uff1a', max_length=128, unique=True, verbose_name='\u4ea7\u54c1\u540d')),
                ('order_num', models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u8ba2\u5355\u6570\u91cf\uff1a', verbose_name='\u8ba2\u5355\u6570\u91cf')),
                ('deliver_date', models.DateField(default=datetime.datetime.now, help_text='\u8bf7\u8f93\u5165\u4ea4\u8d27\u65e5\u671f\uff1a', max_length=8, verbose_name='\u4ea4\u8d27\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='\u5730\u5740')),
                ('picture', models.ImageField(blank=True, upload_to='profiel_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.IntegerField(help_text='\u8bf7\u8f93\u5165\u5458\u5de5\u5de5\u53f7\uff1a', primary_key=True, serialize=False, unique=True, verbose_name='\u5de5\u53f7')),
                ('worker_name', models.CharField(help_text='\u8bf7\u8f93\u5165\u5458\u5de5\u59d3\u540d\uff1a', max_length=32, verbose_name='\u59d3\u540d')),
                ('is_operator', models.BooleanField(help_text='\u662f\u5426\u62c5\u5f53\u4f5c\u4e1a\u5458\u89d2\u8272\uff1f', verbose_name='\u4f5c\u4e1a\u5458\uff1f')),
                ('is_inspector', models.BooleanField(help_text='\u662f\u5426\u62c5\u5f53\u5de1\u68c0\u5458\u89d2\u8272\uff1f', verbose_name='\u5de1\u68c0\u5458\uff1f')),
                ('description', models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u5907\u6ce8\u63cf\u8ff0\uff1a', null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.AddField(
            model_name='produce',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='\u8bf7\u9009\u62e9\u4f5c\u4e1a\u5458\uff1a', null=True, on_delete=django.db.models.deletion.CASCADE, to='lonfly.Worker'),
        ),
        migrations.AddField(
            model_name='produce',
            name='process',
            field=models.ForeignKey(blank=True, help_text='\u8bf7\u9009\u62e9\u5de5\u5e8f\uff1a', null=True, on_delete=django.db.models.deletion.CASCADE, to='lonfly.Process'),
        ),
        migrations.AddField(
            model_name='produce',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lonfly.Products'),
        ),
    ]
